### ISSUE TITLE
Problems playing the DX with a Pfunc. 

### ISSUE THREAD

**Issue by unculcated** [everythingwillbetakenaway/DX7-Supercollider#12]
Works a few times then I get and error

I load the DX function.

( // init
	// Server.killAll
	s.boot;
    ~mainCaller = ("./DX7.scd").loadRelative.wrapAt(-1);
)

(
~patt = Pbind(
     \degree, Rest, // make pattern silent
     \dur, Pseq([1,3,7,2], inf),
     \note, Pseq([50,52,64], inf),
     \vel, Pseq([80,50,10,127], inf),
     \preset, Pseq([2333,3355,33556], inf),
     \put, Pfunc({|values|
         ~mainCaller.value(
             values.note,
             values.vel,
             values.preset)
     })
).play(TempoClock(65/60*4));
)
~patt.stop;
~patt.pause;
~patt.resume;
~patt.free;

After a few runs I get this error. I think it is writing to the DX.afx file. 

Not sure. HELP

----------------------------------------
ERROR: Message 'at' not understood.
RECEIVER:
   nil
ARGS:
   Integer 0
PATH: /Applications/SuperCollider/DX7-Supercollider-master/example.scd

PROTECTED CALL STACK:
	Meta_MethodError:new	0x10b52df80
		arg this = DoesNotUnderstandError
		arg what = nil
		arg receiver = nil
	Meta_DoesNotUnderstandError:new	0x10b52ff40
		arg this = DoesNotUnderstandError
		arg receiver = nil
		arg selector = at
		arg args = [ 0 ]
	Object:doesNotUnderstand	0x1097627c0
		arg this = nil
		arg selector = at
		arg args = nil
	a FunctionDef	0x10faa7808
		sourceCode = "<an open Function>"
		arg item = 0
	Integer:do	0x10dfd1940
		arg this = 145
		arg function = a Function
		var i = 0
	a FunctionDef	0x10faa7938
		sourceCode = "<an open Function>"
		arg x = 64
		arg y = 10
		arg z = 33556
	a FunctionDef	0x10e560840
		sourceCode = "<an open Function>"
	Function:prTry	0x10b888640
		arg this = a Function
		var result = nil
		var thread = a Routine
		var next = nil
		var wasInProtectedFunc = false
	
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Function:protect
		arg this = <instance of Function>
		arg handler = <instance of Function>
		var result = <instance of DoesNotUnderstandError>
	Environment:use
		arg this = <instance of Environment>
		arg function = <instance of Function>
		var result = nil
		var saveEnvir = <instance of Environment>
	< FunctionDef in Method Pbind:embedInStream >
		arg i = 10
		var name = 'put'
		var stream = <instance of FuncStream>
		var streamout = nil
	Integer:forBy
		arg this = 0
		arg endval = 11
		arg stepval = 2
		arg function = <instance of Function>
		var i = 10
		var j = 5
	Pbind:embedInStream
		arg this = <instance of Pbind>
		arg inevent = <instance of Event>
		var event = <instance of Event>
		var sawNil = false
		var streampairs = [*12]
		var endval = 11
	Routine:prStart
		arg this = <instance of Routine>
		arg inval = <instance of Event>
^^ The preceding error dump is for ERROR: Message 'at' not understood.
RECEIVER: nil

**Comment by unculcated** [comment]
Ok, I managed to get it working ok. I might have gone out of range on the preset. 

I added a reset key to the Pfunc, It works but Im getting a lot of 
AILURE IN SERVER /n_free Node 1399 not found
FAILURE IN SERVER /n_free Node 1404 not found
FAILURE IN SERVER /n_free Node 1414 not found
FAILURE IN SERVER /n_free Node 1419 not found
FAILURE IN SERVER /n_free Node 1424 not found 

posts

**Comment by pwqw** [comment]
check 
``` sc
\preset, Pseq([2333,3355,33556], inf),
//                  here ➹➹➹
```
The last preset is 16383
