### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by Clervvil** [everythingwillbetakenaway/DX7-Supercollider#14]
When running your code I get this error:

`ERROR: syntax error, unexpected VAR, expecting NAME or WHILE
  in interpreted text
  line 268 char 4:

  	var lfo, pitchenv, output, randomlfo, multiPitch, lfoAmp;
   ^^^`

**Comment by everythingwillbetakenaway** [comment]
Yes my mistake! Forgot that one while cleaning unused arguments. Fixed now.
