### ISSUE TITLE
method Object:asInt is deprecated and will be removed

### ISSUE THREAD

**Issue by Hyppasus** [everythingwillbetakenaway/DX7-Supercollider#15]
After getting this warning I replaced all occurrences of the `asInt` method with `asInteger` and then the warning disappeared and all functionality was there. After getting this warning I replaced all occurrences of the `asInt` method with `asInteger` and then the warning disappeared and all functionality was there.

**Comment by everythingwillbetakenaway** [comment]
Fixed it, thanks for mentioning it
