### ISSUE TITLE
Missing args to synthdefs

### ISSUE THREAD

**Issue by vivid-synth** [everythingwillbetakenaway/DX7-Supercollider#7]
Also putting this on supercollider's repo (https://github.com/supercollider/supercollider/issues/3466)

If you add ```s.dumpOSC``` to the example code, you'll see that it's not creating ```InfEfx``` with all the args it requires:

```[ 9, "InfEfx", 1001, 2, 1000, "lfo_speed", 4.80054, "lfo_wave", 4,"lfo_phase", 1.5708, "envTrig", 0, "envTrig", 1, "pitchCons", 0.297928, "lfoGet1", 0, "lfoGet2", 1, "tameM", 1, "tameC", 0, "lfo_delay", 1.72212, "lfo_amd", 0 ]```

This is missing ```pitch```, ```gate```, ```lfo_pmd```, and more (these are args without defaults).

This may be causing supernova to segfault.

**Comment by vivid-synth** [comment]
The missing args (for ```InfEfx``` - haven't looked at ```DX7```):

  - ```pitch``` -- not used
  - ```gate``` -- used by ```FreeSelf``` but not initialized - what happens here?
  - ```lfo_pmd``` -- not used
  - ```lfo_sync``` -- not used
  - ```lfo_pms``` - not used
  - ```eg_r1```, ```eg_r2```, ```eg_r3```, ```eg_r4``` -- not used
  - ```eg_r1```, ```eg_r2```, ```eg_r3```, ```eg_r4``` -- not used

**Comment by everythingwillbetakenaway** [comment]
Cleared out those InfEfx unused arguments of InfEfx with last commits. It seems like all DX7 args are in use. Are you still experiencing this problem? I am not using Supernova atm so I cannot test it on my computer.
